name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        # Install dependencies for WeasyPrint: https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#ubuntu-20-04
        run: |
          python -m pip install --upgrade pip
          sudo apt-get -y install python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
          pip install --upgrade pytest pytest-cov coveralls
          pip install PyPDF2 matplotlib libsass
      - name: Install
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          python -m pytest --cov pdf_reports --cov-report term-missing
      - name: Coveralls
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
